FROM ubuntu:latest
LABEL maintainer="sevendollar@gmail.com"
LABEL test="sevendollar@gmail.com"
WORKDIR /terraform
RUN apt-get update && \
    apt-get install -y unzip curl git && \
    curl -o tf https://releases.hashicorp.com/terraform/0.10.0/terraform_0.10.0_linux_amd64.zip?_ga=2.151788921.1355911325.1502345313-1375124468.1501751275 && \
    unzip tf && \
    mv terraform /usr/local/bin/ && \
    rm tf* && \
    rm -rf /var/lib/apt/lists/*
CMD ["terraform"]
